before:
  hooks:
    - go mod tidy

builds:
- env:
  - CGO_ENABLED=0
  goos:
  - darwin
  - linux
  - windows
  goarch:
  - amd64
  - arm
  - arm64
  goarm:
  - "7"
  ignore:
    - goos: darwin
      goarch: arm
    - goos: darwin
      goarch: ppc64le
    - goos: darwin
      goarch: s390x
    - goos: windows
      goarch: ppc64le
    - goos: windows
      goarch: s390x
    - goos: windows
      goarch: arm
      goarm: "5"
    - goos: windows
      goarch: arm
      goarm: "6"
    - goos: windows
      goarch: arm
      goarm: "7"
    - goos: windows
      goarch: arm64
    - goos: freebsd
      goarch: ppc64le
    - goos: freebsd
      goarch: s390x
    - goos: freebsd
      goarch: arm
      goarm: "5"
    - goos: freebsd
      goarch: arm
      goarm: "6"
    - goos: freebsd
      goarch: arm
      goarm: "7"
    - goos: freebsd
      goarch: arm64
  flags:
  - -trimpath
  ldflags:
  - -s -w -X github.com/ChristopherHX/gitea-actions-runner/cmd.version={{ .Summary }}
  binary: >-
    {{ .ProjectName }}-
    {{- .Version }}-
    {{- .Os }}-
    {{- if eq .Arch "amd64" }}amd64
    {{- else if eq .Arch "amd64_v1" }}amd64
    {{- else if eq .Arch "386" }}386
    {{- else }}{{ .Arch }}{{ end }}
    {{- if .Arm }}-{{ .Arm }}{{ end }}
  no_unique_dist_dir: true
  hooks:
    post:
      - cmd: xz -k -9 {{ .Path }}
        dir: ./dist/
      - cmd: sh .goreleaser.checksum.sh {{ .Path }}
      - cmd: sh .goreleaser.checksum.sh {{ .Path }}.xz

archives:
  - format: binary
    name_template: "{{ .Binary }}"
    allow_different_binary_count: true

checksum:
  name_template: 'checksums.txt'
  extra_files:
      - glob: ./**.xz

snapshot:
  name_template: "{{ .Branch }}-devel"

gitea_urls:
  api: https://gitea.com/api/v1
  download: https://gitea.com

release:
  extra_files:
    - glob: ./**.xz
    - glob: ./**.xz.sha256

# yaml-language-server: $schema=https://goreleaser.com/static/schema-pro.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj
