name: build/release

on:
  push:

jobs:
  post:
    needs: pre
    runs-on: ubuntu-latest
    steps:
      - run: ${{ tojson(needs) }}
        shell: cat {0}
    if: failure()
  pre:
    runs-on: ubuntu-latest
    steps:
      - run: echo "out=Test" > "$GITHUB_ENV"
        id: out
      - run: exit 1
    outputs:
      out: ${{ env.out }}