name: test-artifacts

on:
  push:

jobs:
  test-artifacts:
    runs-on: ubuntu-latest
    steps:
    - run: mkdir -p path/to/artifact

    - run: echo hello > path/to/artifact/world.txt

    - uses: actions/upload-artifact@v3
      with:
        name: my-artifact
        path: path/to/artifact/world.txt