name: build/release

on:
  push:

env:
  GOPATH: /go_path
  GOCACHE: /go_cache

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # all history for all branches and tags
      - uses: actions/setup-go@v3
        if: env.ACT
        with:
          go-version: '>=1.20.1'
      - uses: https://gitea.com/actions/go-hashfiles@v0.0.1
        id: hash-go
        with:
          patterns: |
            go.mod
            go.sum
      - name: cache go
        id: cache-go
        uses: https://github.com/actions/cache@v3
        with:
          path: |
            /go_path
            /go_cache
          key: go_path-${{ steps.hash-go.outputs.hash || hashfiles('go.mod', 'go.sum')}}

      - name: Run GoReleaser
        uses: https://github.com/goreleaser/goreleaser-action@v4
        if: startsWith(github.ref, 'refs/tags/')
        with:
          version: latest
          args: release --clean
        env:
          GORELEASER_FORCE_TOKEN: 'gitea'
          GITEA_TOKEN: ${{ secrets.GITHUB_TOKEN }}

