name: test-cache

on:
  push:

jobs:
  test-cache:
    runs-on: ubuntu-latest
    steps:
    - run: echo hello > world.txt

    - name: Cache Primes
      id: cache-primes
      uses: actions/cache@v3
      with:
        path: world.txt
        key: ${{ runner.os }}-primes