name: checks
on: [push]

env:
  GOPROXY: https://goproxy.io,direct

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.17
      - uses: actions/checkout@v3
      - uses: Jerome1337/golint-action@v1.0.2
      #- name: golangci-lint
      #  uses: golangci/golangci-lint-action@v3
      #  with:
          # Optional: version of golangci-lint to use in form of v1.2 or v1.2.3 or `latest` to use the latest version
      #    version: v1.29