# docker-compose.yml
networks:
  runner:
    external: false
volumes:
  runner:
    driver: local
  runner-externals:
    driver: local
  gitea-runner-data:
    driver: local
  socket:
    driver: local
services:
  runner:
    image: ghcr.io/christopherhx/gitea-actions-runner:ubuntu-focal-latest
    environment:
      - GITEA_INSTANCE_URL=https://gitea.com/                            # Your Gitea Instance to register to
      - GITEA_RUNNER_REGISTRATION_TOKEN=XXXXXXXXXXXXXXXXXXXXXXX          # The Gitea registration token
      - GITEA_RUNNER_LABELS=self-hosted                                  # The labels of your runner (comma separated)
    restart: always
    user: root
    networks:
      - runner
    volumes:
      - gitea-runner-data:/data                 # Persist runner registration across updates
      - runner:/home/runner/_work               # DIND
      - runner-externals:/home/runner/externals # DIND
      - socket:/var/run
    depends_on:
      - docker
  docker:
    image: docker:dind
    restart: always
    privileged: true
    networks:
      - runner
    volumes:
      - runner:/home/runner/_work
      - runner-externals:/home/runner/externals
      - socket:/var/run