# docker-compose.yml 
networks:
  runner:
    external: false
volumes:
  runner:
    driver: local
  runner-externals:
    driver: local
  gitea-runner-data:
    driver: local
  docker-certs:
    driver: local
services:
  runner:
    image: ghcr.io/christopherhx/gitea-actions-runner:latest
    environment:
      - GITEA_INSTANCE_URL=https://gitea.com                            # Your Gitea Instance to register to
      - GITEA_RUNNER_REGISTRATION_TOKEN=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX # The Gitea registration token
      - GITEA_RUNNER_LABELS=self-hosted                                 # The labels of your runner (comma separated)
      - DOCKER_TLS_CERTDIR=/certs                                       # DIND
      - DOCKER_CERT_PATH=/certs/client                                  # DIND
      - DOCKER_TLS_VERIFY=1                                             # DIND
      - DOCKER_HOST=tcp://docker:2376                                   # DIND
    restart: always
    networks:
      - runner
    volumes:
      - gitea-runner-data:/data                 # Persist runner registration across updates
      - runner:/home/runner/_work               # DIND
      - runner-externals:/home/runner/externals # DIND
      - docker-certs:/certs                     # DIND
    depends_on:
      - docker
  docker:
    image: docker:dind-rootless
    restart: always
    privileged: true
    environment:
      - DOCKER_TLS_CERTDIR=/certs
    networks:
      - runner
    volumes:
      - runner:/home/runner/_work
      - runner-externals:/home/runner/externals
      - docker-certs:/certs
      - ./var-lib-docker:/var/lib/docker
