on:
  push:
    branches:
    - main
  workflow_dispatch:
    inputs:
      gitea-runner-tag:
        type: string
  workflow_call:
    inputs:
      gitea-runner-tag:
        type: string
  
jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
        - file: Dockerfile
          build-args: ''
          tag-prefix: ''
        - file: Dockerfile.medium
          build-args: |
            BASE_IMAGE=catthehacker/ubuntu:act-20.04
          tag-prefix: ubuntu-focal-
        - file: Dockerfile.medium
          build-args: |
            BASE_IMAGE=catthehacker/ubuntu:act-22.04
          tag-prefix: ubuntu-jammy-
        - file: Dockerfile.medium
          build-args: |
            BASE_IMAGE=catthehacker/ubuntu:act-latest
          tag-prefix: ubuntu-
    permissions:
      contents: read
      packages: write
    steps:
    - uses: actions/checkout@v3
    -
      name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    -
      name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - run: |
        echo "LOWNER<<EOF23" >> $GITHUB_ENV
        echo $(echo "$OWNER" | tr '[:upper:]' '[:lower:]') >> $GITHUB_ENV
        echo "EOF23" >> $GITHUB_ENV
      shell: bash
      env:
        OWNER: ${{github.repository_owner}}
    -
      name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ${{ matrix.Dockerfile || 'Dockerfile' }}
        platforms: linux/amd64,linux/arm64
        push: true
        build-args: ${{ matrix.build-args || '' }}
        tags: ghcr.io/${{env.LOWNER}}/gitea-actions-runner:${{ matrix.tag-prefix }}${{ inputs.gitea-runner-tag || 'nightly' }},ghcr.io/${{env.LOWNER}}/gitea-actions-runner:${{ matrix.tag-prefix }}${{ inputs.gitea-runner-tag && 'latest' || 'nightly' }}
