on:
  push:
    branches:
    - main
  workflow_dispatch:
    inputs:
      gitea-runner-tag:
        type: string
  workflow_call:
    inputs:
      gitea-runner-tag:
        type: string
  
jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        release: [jammy, focal, latest]
      fail-fast: false
    steps:
    - uses: actions/checkout@v3
    -
      name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    -
      name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - run: |
        echo "LOWNER<<EOF23" >> $GITHUB_ENV
        echo $(echo "$OWNER" | tr '[:upper:]' '[:lower:]') >> $GITHUB_ENV
        echo "EOF23" >> $GITHUB_ENV
      shell: bash
      env:
        OWNER: ${{github.repository_owner}}
    - 
      name: Replace Docker Image in Dockerfile
      run: |
        if [ "${{ matrix.release }}" == "jammy" ]; then
          version="22.04"
        elif [ "${{ matrix.release }}" == "focal" ]; then
          version="20.04"
        else
          version="latest"
        fi
        sed -i "s/FROM catthehacker\/ubuntu:act-latest.*/FROM catthehacker\/ubuntu:act-${version}-20231008/" Dockerfile
        sed -i "s/ENV GITEA_RUNNER_LABELS=ubuntu-latest/ENV GITEA_RUNNER_LABELS=ubuntu-${version}/" Dockerfile
    -
      name: Build and push
      uses: docker/build-push-action@v3
      with:
        context: .
        platforms: linux/amd64,linux/arm64
        push: true
        tags: ghcr.io/${{env.LOWNER}}/gitea-actions-runner:ubuntu-${{ matrix.release }}
