name: build/release

on:
  push:

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # all history for all branches and tags
      - uses: actions/setup-go@v4
        with:
          go-version: '>=1.20.1'

      - name: Build
        if: "!startsWith(github.ref, 'refs/tags/')"
        run: |
          go build

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v4
        if: startsWith(github.ref, 'refs/tags/')
        with:
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # - name: create-output
      #   if: startsWith(github.ref, 'refs/tags/')
      #   uses: actions/github-script@v7
      #   with:
      #     script: core.setOutput("", ${{ tojson(github.ref)}}.substring("refs/tags/v".length))

  container:
    if: startsWith(github.ref, 'refs/tags/')
    uses: ./.github/workflows/build_container.yml
    permissions:
      contents: read
      packages: write
    with:
      gitea-runner-tag: ${{ github.ref_name }}
