on:
  push:
    branches:
    - main
  workflow_dispatch:
    inputs:
      gitea-runner-tag:
        type: string
  workflow_call:
    inputs:
      gitea-runner-tag:
        type: string
  
jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - uses: actions/checkout@v3
    -
      name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    -
      name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - run: |
        echo "LOWNER<<EOF23" >> $GITHUB_ENV
        echo $(echo "$OWNER" | tr '[:upper:]' '[:lower:]') >> $GITHUB_ENV
        echo "EOF23" >> $GITHUB_ENV
      shell: bash
      env:
        OWNER: ${{github.repository_owner}}
    -
      name: Build and push
      uses: docker/build-push-action@v3
      with:
        context: .
        platforms: linux/amd64,linux/arm64
        push: true
        build-args: |
          GITEA_ACTIONS_RUNNER_VERSION=${{ inputs.gitea-runner-tag || 'v0.0.6' }}
        tags: ghcr.io/${{env.LOWNER}}/gitea-actions-runner:${{ inputs.gitea-runner-tag || 'v0.0.6' }},ghcr.io/${{env.LOWNER}}/gitea-actions-runner:${{ inputs.gitea-runner-tag && 'latest' || 'v0.0.6' }}
